### ISSUE TITLE
scalarTotalET sometimes not being calculated correctly

### ISSUE THREAD

**Issue by arbennett** [CH-Earth/summa#327]
While making some water balance plotting scripts I came across some inconsistency in how the variable `scalarTotalET` is output . Some HRUs calculate this value correctly while others just have zeros.

The correct calculation (per the SUMMA code) should be:
`scalarTotalET = scalarGroundEvaporation + scalarCanopyEvaporation + scalarCanopyTranspiration`

Below is a plot showing one of the locations where this issue was present.  You can see that the manual sum of the components is simply the ground evaporation in this case, but the derived `scalarTotalET_mean` is zero across the timeseries.  

![totalet_issue](https://user-images.githubusercontent.com/7518706/37743564-e3ba19be-2d27-11e8-9c9f-36361a22b7c4.png)

This does not appear to be soil or vegetation type related as far as I can tell.  Can anybody else reproduce this issue?

**Comment by bartnijssen** [comment]
@arbennett: Are these SUMMA calculated means? Can you reproduce this with the instantaneous values?

**Comment by arbennett** [comment]
Those were SUMMA calculated means.  It appears reproducible with instantaneous values.  Below is a plot. 

![totalet_issue_timestep](https://user-images.githubusercontent.com/7518706/37744708-e35bab44-2d2d-11e8-806c-79f9f37d4cd3.png)

**Comment by bartnijssen** [comment]
@arbennett: Given that this does not happen for every cell in your Columbia domain - can you include any additional info that makes this grid cell different? (veg type, soil type, always snow covered, never snow covered, etc.). Also - would it be possible to update the plots with actual dates rather than day numbers?

**Comment by arbennett** [comment]
I haven't been able to identify anything unique about these locations.  They don't share a common vegetation type, and while they all share the same soil type (clay), there are HRU in this run that have those characteristics and calculate the `scalarTotalET` as expected. None of the issue sites are either covered nor empty of snow all the time. There are 9 of 24 in the range `7009-7032` which show this issue.  They are `[7010 7012 7013 7015 7017 7018 7021 7028 7032]`.
