### ISSUE TITLE
check canopyTemp and canopyIce in restart file

### ISSUE THREAD

**Issue by nmizukami** [CH-Earth/summa#362]
When using saved restart file to start the simulation,  read_icond.f90 https://github.com/NCAR/summa/blob/825893588185f064ad07b9b51241ddb8b24669f6/build/source/engine/check_icond.f90#L152 checks if canopy Ice cannot exist when canopy temperature is above freezing.  The model is terminated if this situation happens in the restart file.    However, this situation can happen at any time steps during the simulations (Also, the model does not seem to check this situation happen each time step).   see the
[canopyTemp_vs_canopyICE.txt](https://github.com/NCAR/summa/files/4048700/canopyTemp_vs_canopyICE.txt)

I am wondering if this check can be removed safely.

**Comment by wknoben** [comment]
Addressed in #481 by adding a threshold to the check that happens for restart files, so closing this for now.
