### ISSUE TITLE
Canopy ice content check during initial conditions interferes with restart files under certain conditions

### ISSUE THREAD

**Issue by wknoben** [CH-Earth/summa#474]
#### Bug Report
- SUMMA v3.0 and above, but presumably has existed for longer
- gcc v7.3.0
- Linux/macOS
- Relevant settings: n/a

Error ```FATAL ERROR: summa_readRestart/check_icond/canopy ice > 0 when canopy temperature > Tfreeze``` can be triggered in cases where a restart file has a non-zero canopy snow/ice state but temperature > Tfreeze. This is not always a physical impossibility in cases when:
- T > Tfreeze when restart file is created and on the next timestep, but canopy ice content has not fully melted (yet)
- T < Tfreeze and canopy ice > 0 when restart file is created and T > Tfreeze on the next timestep

During regular simulations both cases should run fine, but such cases do not make it through a restart. It is not entirely clear to me why this check appears in the ICs and I therefore don't know the best approach to solving this. Thoughts?

**Comment by DaveCasson** [comment]
This issue is also appearing in several simulations and causing crashes. Would be great to have a resolution.

**Comment by wknoben** [comment]
Fixed in #481 Closing this for now until we have a reason to revisit the warning/error approach applied
