### ISSUE TITLE
Fatal error in gru index, vector of residuals contains NaN value(s).

### ISSUE THREAD

**Issue by JoaquinSaavC** [CH-Earth/summa#554]
Hi, we are new to SUMMA modelling and we keep having this error:

FATAL ERROR: run_oneGRU (gru index = 1)/run_oneHRU (hruId = 10396000)/coupled_em/opSplittin/varSubstep/systemSolv/eval8summa/computResid/vector of residuals contains NaN value(s)

Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG

We've checked every file containing gru or hru information and can't find the source of the fatal error. We would be most grateful for any kind of guidance in solving this issue.

**Comment by wknoben** [comment]
I assume this is solved? 

Just adding a brief response in case others come looking: these errors indicate that numerical solver is unable to find a solution for the equations at a given time step. The most common causes I've seen for this are:
- Forcing variables in the wrong units (see here: https://summa.readthedocs.io/en/latest/input_output/SUMMA_input/#meteorological-forcing-files)
- Forcing variables contain physically unrealistic values, which causes certain equations to break (e.g. zero pressure)
